ALTER TABLE cw_wikis MODIFY COLUMN wiki_closed SMALLINT NOT NULL DEFAULT '0';
ALTER TABLE cw_wikis MODIFY COLUMN wiki_inactive SMALLINT NOT NULL DEFAULT '0';
ALTER TABLE cw_wikis MODIFY COLUMN wiki_inactive_exempt SMALLINT NOT NULL DEFAULT '0';
ALTER TABLE cw_wikis MODIFY COLUMN wiki_deleted SMALLINT NOT NULL DEFAULT '0';
ALTER TABLE cw_wikis MODIFY COLUMN wiki_locked SMALLINT NOT NULL DEFAULT '0';
